### ISSUE TITLE
[Error  :   BepInEx] Could not load [Character Morpher 0.2.0] because it has missing dependencies: KKABMX.Core (v4.4.6 or newer)

### ISSUE THREAD

**Issue by theway2377** [Prolo1/Character-Morpher#1]
HS2_Character_Morpher.zip [Error  :   BepInEx] Could not load [Character Morpher 0.2.0] because it has missing dependencies: KKABMX.Core (v4.4.6 or newer)

**Comment by theway2377** [comment]
Thanks, reinstalling ABMX helped.  Although it is odd because ABMX has not had a new version in 2 years, and I updated to R8 recently, just before 8.1. Thanks for Character Morpher!  The only thing odd I noticed was that under "Body Controls", the "Head" seemed to morph the boobs, while the "Boobs" seemed to morph both head and boobs.  I recorded video linked
https://imgur.com/a/iyY26JM

**Comment by Prolo1** [comment]
I figured it out, turns out I just had some values mixed up, you can change this for now by using the advanced settings and changing them to what you see in this image 
![The true settings](https://media.discordapp.net/attachments/897794665632395274/976661637161427014/unknown.png) (you should have one extra slot in brests, just change it to be any of the other values that are there like 1)

**Comment by Prolo1** [comment]
I added the fix as a [release](https://github.com/Prolo1/Character-Morpher/releases/tag/V0.2.0.R1) so everything should be good from here. Good night world.
