### ISSUE TITLE
Not working on KK BRX14

### ISSUE THREAD

**Issue by Tarried** [Prolo1/Character-Morpher#2]
Hi, I'm on Windows 10, running a fresh install of KK BetterRepack RX14. The only change I've made is to add Character-Morpher plugin.

I can see the tab on the side-panel; I can see and interact with all the toggles and sliders, I can even target and load a base card. 

The issue is that none of these do anything: regardless of which card I designate as the target, or what character is currently loaded, or which boxes are enabled at the top: none of the sliders do anything. Like, I will change the values of any and all of the sliders, and nothing whatsoever happens to the loaded character.

I don't have KKS loaded, so I can't test it in that game. Can you, (or anyone else) verify that it's working in  KK?

**Comment by Prolo1** [comment]
I'm close to releasing what I have for the next mod version, which should fix the problem (or create more programming is weird). What likely happened is an error popped up due to a mod dependency crashing one of the functions and causing it never to run again (thanks unity). I've made a lot of changes and updated dependencies in the current version, all I'm doing now is testing that it works on each game. There's also one more issue with my current code that I'm trying to fix, but that's just a matter of time.

Thanks for the report

**Comment by Prolo1** [comment]
I'm going to say this now before I forget again but as of now this stupid program just hates me. I fixed the issue I was talking about before but now for some reason, the bone data won't load so I'm fixing that now. Let's see how long this one takes 🙄

**Comment by Prolo1** [comment]
Jobs done. Release incoming.
